In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# New Section

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
path ="/content/drive/MyDrive/Colab Notebooks/archive/Bangalore.csv"

In [3]:
df= pd.read_csv(path)

In [4]:
df.head()

      Price  Area  ... Wardrobe  Refrigerator
0  30000000  3340  ...        0             0
1   7888000  1045  ...        0             0
2   4866000  1179  ...        0             0
3   8358000  1675  ...        0             0
4   6845000  1670  ...        0             0

[5 rows x 40 columns]

Warning: Total number of columns (40) exceeds max_columns (20) limiting to first (20) columns.

In [5]:
df.tail()

         Price  Area       Location  ...  Sofa  Wardrobe  Refrigerator
6202   5364000   590     Chandapura  ...     9         9             9
6203   8716000  1179  Kasavanahalli  ...     9         9             9
6204   7373000  1143  Kasavanahalli  ...     9         9             9
6205   4985000  1680  Kasavanahalli  ...     9         9             9
6206  10900000  1162  Kasavanahalli  ...     9         9             9

[5 rows x 40 columns]

In [6]:
df.describe()

              Price         Area  ...     Wardrobe  Refrigerator
count  6.207000e+03  6207.000000  ...  6207.000000   6207.000000
mean   1.058510e+07  1526.094248  ...     6.171097      6.210569
std    1.410943e+07   764.845609  ...     4.178546      4.124430
min    2.000000e+06   415.000000  ...     0.000000      0.000000
25%    5.000000e+06  1110.000000  ...     0.000000      0.000000
50%    7.368000e+06  1340.000000  ...     9.000000      9.000000
75%    1.070000e+07  1662.500000  ...     9.000000      9.000000
max    3.000000e+08  9900.000000  ...     9.000000      9.000000

[8 rows x 39 columns]

In [7]:

df.describe().T

                      count          mean  ...         75%          max
Price                6207.0  1.058510e+07  ...  10700000.0  300000000.0
Area                 6207.0  1.526094e+03  ...      1662.5       9900.0
No. of Bedrooms      6207.0  2.556952e+00  ...         3.0          7.0
Resale               6207.0  7.878202e-02  ...         0.0          1.0
MaintenanceStaff     6207.0  6.208797e+00  ...         9.0          9.0
Gymnasium            6207.0  6.461576e+00  ...         9.0          9.0
SwimmingPool         6207.0  6.436121e+00  ...         9.0          9.0
LandscapedGardens    6207.0  6.382471e+00  ...         9.0          9.0
JoggingTrack         6207.0  6.396649e+00  ...         9.0          9.0
RainWaterHarvesting  6207.0  6.373933e+00  ...         9.0          9.0
IndoorGames          6207.0  6.348639e+00  ...         9.0          9.0
ShoppingMall         6207.0  6.207024e+00  ...         9.0          9.0
Intercom             6207.0  6.420010e+00  ...         9.0          9.0
SportsFacility       6207.0  6.332206e+00  ...         9.0          9.0
ATM                  6207.0  6.210246e+00  ...         9.0          9.0
ClubHouse            6207.0  6.397293e+00  ...         9.0          9.0
School               6207.0  6.208152e+00  ...         9.0          9.0
24X7Security         6207.0  6.394071e+00  ...         9.0          9.0
PowerBackup          6207.0  6.455292e+00  ...         9.0          9.0
CarParking           6207.0  6.353633e+00  ...         9.0          9.0
StaffQuarter         6207.0  6.240696e+00  ...         9.0          9.0
Cafeteria            6207.0  6.236668e+00  ...         9.0          9.0
MultipurposeRoom     6207.0  6.345416e+00  ...         9.0          9.0
Hospital             6207.0  6.188980e+00  ...         9.0          9.0
WashingMachine       6207.0  6.210569e+00  ...         9.0          9.0
Gasconnection        6207.0  6.233768e+00  ...         9.0          9.0
AC                   6207.0  6.211374e+00  ...         9.0          9.0
Wifi                 6207.0  6.171097e+00  ...         9.0          9.0
Children'splayarea   6207.0  6.453037e+00  ...         9.0          9.0
LiftAvailable        6207.0  6.438537e+00  ...         9.0          9.0
BED                  6207.0  6.211052e+00  ...         9.0          9.0
VaastuCompliant      6207.0  6.311100e+00  ...         9.0          9.0
Microwave            6207.0  6.210569e+00  ...         9.0          9.0
GolfCourse           6207.0  6.181569e+00  ...         9.0          9.0
TV                   6207.0  6.210569e+00  ...         9.0          9.0
DiningTable          6207.0  6.210569e+00  ...         9.0          9.0
Sofa                 6207.0  6.210569e+00  ...         9.0          9.0
Wardrobe             6207.0  6.171097e+00  ...         9.0          9.0
Refrigerator         6207.0  6.210569e+00  ...         9.0          9.0

[39 rows x 8 columns]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6207 entries, 0 to 6206
Data columns (total 40 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Price                6207 non-null   int64
 1   Area                 6207 non-null   int64
 2   Location             6207 non-null   object
 3   No. of Bedrooms      6207 non-null   int64
 4   Resale               6207 non-null   int64
 5   MaintenanceStaff     6207 non-null   int64
 6   Gymnasium            6207 non-null   int64
 7   SwimmingPool         6207 non-null   int64
 8   LandscapedGardens    6207 non-null   int64
 9   JoggingTrack         6207 non-null   int64
 10  RainWaterHarvesting  6207 non-null   int64
 11  IndoorGames          6207 non-null   int64
 12  ShoppingMall         6207 non-null   int64
 13  Intercom             6207 non-null   int64
 14  SportsFacility       6207 non-null   int64
 15  ATM                  6207 non-null   int64
 16  ClubHouse            6207 non-null   int64
 17  School               6207 non-null   int64
 18  24X7Security         6207 non-null   int64
 19  PowerBackup          6207 non-null   int64
 20  CarParking           6207 non-null   int64
 21  StaffQuarter         6207 non-null   int64
 22  Cafeteria            6207 non-null   int64
 23  MultipurposeRoom     6207 non-null   int64
 24  Hospital             6207 non-null   int64
 25  WashingMachine       6207 non-null   int64
 26  Gasconnection        6207 non-null   int64
 27  AC                   6207 non-null   int64
 28  Wifi                 6207 non-null   int64
 29  Children'splayarea   6207 non-null   int64
 30  LiftAvailable        6207 non-null   int64
 31  BED                  6207 non-null   int64
 32  VaastuCompliant      6207 non-null   int64
 33  Microwave            6207 non-null   int64
 34  GolfCourse           6207 non-null   int64
 35  TV                   6207 non-null   int64
 36  DiningTable          6207 non-null   int64
 37  Sofa                 6207 non-null   int64
 38  Wardrobe             6207 non-null   int64
 39  Refrigerator         6207 non-null   int64
dtypes: int64(39), object(1)
memory usage: 1.9+ MB

In [9]:

df.columns

Index(['Price', 'Area', 'Location', 'No. of Bedrooms', 'Resale',
       'MaintenanceStaff', 'Gymnasium', 'SwimmingPool', 'LandscapedGardens',
       'JoggingTrack', 'RainWaterHarvesting', 'IndoorGames', 'ShoppingMall',
       'Intercom', 'SportsFacility', 'ATM', 'ClubHouse', 'School',
       '24X7Security', 'PowerBackup', 'CarParking', 'StaffQuarter',
       'Cafeteria', 'MultipurposeRoom', 'Hospital', 'WashingMachine',
       'Gasconnection', 'AC', 'Wifi', 'Children'splayarea', 'LiftAvailable',
       'BED', 'VaastuCompliant', 'Microwave', 'GolfCourse', 'TV',
       'DiningTable', 'Sofa', 'Wardrobe', 'Refrigerator'],
      dtype='object')

In [10]:
df.sort_values(by="Price")

          Price  Area                    Location  ...  Sofa  Wardrobe  Refrigerator
5099    2000000  2730               Sarjapur Road  ...     9         9             9
677     2096000   645                 Anekal City  ...     0         0             0
2205    2100000  2814                Banashankari  ...     9         9             9
6164    2100000  1477     Electronic City Phase 2  ...     9         9             9
5906    2150000  1013                       Begur  ...     9         9             9
...         ...   ...                         ...  ...   ...       ...           ...
6144  200000000  1070                  Kumbalgodu  ...     9         9             9
819   202700000  9900                      Hebbal  ...     0         0             0
4833  260000000   731  Manyata Tech Park Nagawara  ...     9         9             9
4962  270000000  1225                 Anekal City  ...     9         9             9
4834  300000000   785                 Bommasandra  ...     9         9             9

[6207 rows x 40 columns]

In [11]:
df.describe()

              Price         Area  ...     Wardrobe  Refrigerator
count  6.207000e+03  6207.000000  ...  6207.000000   6207.000000
mean   1.058510e+07  1526.094248  ...     6.171097      6.210569
std    1.410943e+07   764.845609  ...     4.178546      4.124430
min    2.000000e+06   415.000000  ...     0.000000      0.000000
25%    5.000000e+06  1110.000000  ...     0.000000      0.000000
50%    7.368000e+06  1340.000000  ...     9.000000      9.000000
75%    1.070000e+07  1662.500000  ...     9.000000      9.000000
max    3.000000e+08  9900.000000  ...     9.000000      9.000000

[8 rows x 39 columns]

In [12]:
df["Price"]

0       30000000
1        7888000
2        4866000
3        8358000
4        6845000
          ...
6202     5364000
6203     8716000
6204     7373000
6205     4985000
6206    10900000
Name: Price, Length: 6207, dtype: int64

In [13]:
df.Price

0       30000000
1        7888000
2        4866000
3        8358000
4        6845000
          ...
6202     5364000
6203     8716000
6204     7373000
6205     4985000
6206    10900000
Name: Price, Length: 6207, dtype: int64

In [14]:
np.mean?

In [15]:
np.mean(df['Price'])

10585104.825519575

In [16]:
df['Location'].value_counts()

Electronic City Phase 2    232
RR Nagar                   217
Begur                      186
Varthur                    168
Kumaraswamy Layout         154
                          ...
Kambipura                    1
Whitefield Road              1
HAL                          1
hebbal kempapura             1
Krishna Garden Road          1
Name: Location, Length: 302, dtype: int64

In [17]:
 avg_df = df.groupby('Location').mean()

In [18]:
avg_df.head()

                                        Price  ...  Refrigerator
Location                                       ...
5th Phase                        1.078500e+07  ...           9.0
5th Stage BEML Layout            6.862000e+06  ...           9.0
5th Stage Raja Rajeshwari Nagar  5.128400e+06  ...           9.0
6th phase jp nagar               7.840000e+06  ...           9.0
7th Phase JP Nagar               1.870000e+07  ...           9.0

[5 rows x 39 columns]

In [19]:
list(df['Location'].unique())

['JP Nagar Phase 1',
 'Dasarahalli on Tumkur Road',
 'Kannur on Thanisandra Main Road',
 'Doddanekundi',
 'Kengeri',
 'Horamavu',
 'Thanisandra',
 'Ramamurthy Nagar',
 'Whitefield Hope Farm Junction',
 'Electronic City Phase 1',
 'Yelahanka',
 'Anjanapura',
 'Jalahalli',
 'Kasavanahalli',
 'Bommasandra',
 'Bellandur',
 'RR Nagar',
 'Begur',
 'Hosa Road',
 'Sahakar Nagar',
 'Kadugodi',
 'Jakkur',
 'Jigani',
 'Krishnarajapura',
 'Brookefield',
 'Banashankari',
 'Nelamangala',
 'Attibele',
 'Banaswadi',
 'Kodigehalli',
 'ITPL',
 'Uttarahalli Hobli',
 'Chikkagubbi on Hennur Main Road',
 'Varthur',
 'Vidyaranyapura',
 'Electronic City Phase 2',
 'J. P. Nagar',
 'K. Chudahalli',
 'Narayanaghatta',
 'Anekal City',
 'Sarjapur',
 'Koramangala',
 'Hebbal',
 'Budigere Cross',
 'Bommanahalli',
 'Electronics City',
 'Chikkalasandra',
 'Kogilu',
 'Nayandahalli',
 'Bilekahalli',
 'Muneshwara Nagar',
 'Junnasandra',
 'Narayanapura on Hennur Main Road',
 'Kothanur',
 'Kadugodi Industrial Area',
 'Sarjapur Road Wipro To Railway Crossing',
 'RMV Extension Stage 2',
 'Kudlu',
 'Talaghattapura',
 'Kumbalgodu',
 'Carmelaram',
 'Uttarahalli',
 'Anagalapura Near Hennur Main Road',
 'Avalahalli Off Sarjapur Road',
 'R T  Nagar',
 'JP Nagar Phase 7',
 'Subramanyapura',
 'JP Nagar Phase 4',
 'JP Nagar Phase 8',
 'Amruthahalli',
 'Nagarbhavi',
 'Chandapura',
 'Marsur',
 'JP Nagar Phase 3',
 'JP Nagar Phase 9',
 'Gottigere',
 'Kanakapura Road Beyond Nice Ring Road',
 'Harlur',
 'Konanakunte',
 'Richmond Town',
 'Jayanagar',
 'Domlur',
 'Devanahalli',
 'Hulimavu',
 'Kumaraswamy Layout',
 'Bikasipura',
 'Singasandra',
 'JP Nagar Phase 6',
 'Sanjaynagar',
 'CV Raman Nagar',
 'Padmanabhanagar',
 'Hennur',
 'KPC Layout',
 'R.K. Hegde Nagar',
 'Kannamangala',
 'Yerthiganahalli',
 'Badamanavarthekaval',
 'Kanakapura',
 'Bannerughatta',
 'BTM Layout',
 'Kuvempu Layout on Hennur Main Road',
 'Marathahalli',
 'Rajajinagar',
 'Whitefield',
 'RMV',
 'Bileshivale',
 'Nagawara',
 'HSR Layout',
 'Anjanapura Township',
 'Hurulichikanahalli',
 'Devarachikkana Halli',
 'Sampangiram Nagar',
 'Armane Nagar',
 'Basavanagudi',
 'Yeshwantpur',
 'Battarahalli',
 'K C Krishna Reddy Layout',
 'Adugodi',
 'Kammanahalli',
 'Kalyan Nagar',
 'Kudlu Gate',
 'Kodipalya',
 'Kaggadasapura',
 'Malleswaram',
 'Akshayanagar',
 'Kammmanhalli',
 'Lingarajapuram',
 'Indira Nagar',
 'Nagasandra',
 'Kaval Byrasandra',
 'Sanjay Nagar',
 'Sanjeevini Nagar',
 'Cooke Town',
 'Frazer Town',
 'Vasanth Nagar',
 'NRI Layout',
 'Dasarahalli',
 'Kalkere',
 'Kartik Nagar',
 'Sarjapur Road Till Wipro',
 'hebbal kempapura',
 'Cox Town',
 'Bendre Nagar',
 'Hosakerehalli',
 'Byrathi',
 'Narayanapura',
 'Chamrajpet',
 'Kodihalli on Old Airport Road',
 'Nandini Layout',
 'Ullal Uppanagar',
 'Doddaballapur',
 'Murugesh Palya',
 'Annapurneshwari Nagar',
 'Lingadheeranahalli',
 'Chandra Layout Extension',
 'BTM Layout 2nd Stage',
 '8th Phase JP Nagar',
 'Dodda Banaswadi',
 'Sidedahalli',
 'Hallehalli',
 'HBR Layout',
 'Rajarajeshwari nagar',
 'Uttarahalli Main Road',
 'Poornapragna Housing Society Layout',
 '5th Stage Raja Rajeshwari Nagar',
 'RR Nagar Main Road',
 'DrVishnuvardhan Road',
 'Bharath Housing Society Layout',
 'Hennur Main Road',
 'JP Nagar Phase 5',
 '5th Phase',
 'Kadugondanahalli',
 'Hosa Road Junction',
 'AGS Layout Arehalli',
 'Hosur Main Road',
 'Uttarahalli Road',
 'Poornaprajna Layout',
 'Poorna Pragna Layout',
 'Banashankari 5th stage',
 'Channasandra Layout',
 'JP Nagar 8th Phase',
 'Volagerekallahalli',
 'Mysore Road',
 'Thanisandra Main Road',
 'Koppa Begur Road',
 'Sarjapur Road',
 'Ulsoor',
 'Kathriguppe',
 'Babusabpalya',
 'AECS Layout A Block Singasandra',
 'KR Puram Bhattarahalli',
 'Raja Rajeshwari Nagar 5th Stage',
 'RMV 2nd Stage',
 'Kambipura',
 'Pattanagere Main Road',
 'Ashwathkatte Road',
 'BEML Layout 5th Stage',
 'Shivaji Nagar',
 'Bagalur',
 'Sarjapur Attibele',
 'Domlur Layout',
 'sarjapura attibele road',
 'TC Palya Road',
 'ISRO Layout',
 'Munnekollal',
 'Infantry Road',
 'Richards Town',
 'Pattanagere',
 'Benson Town',
 'Sri Krishna Garden Layout',
 'Kenchena Halli Road',
 'Rajarajeswari Nagar',
 'Bannerghatta Main Road',
 'Mahadevapura',
 'Babusa Palya',
 'Kumaraswamy Layout Vittal Nagar',
 'Ideal Homes Co Operative Housing Society',
 '5th Stage BEML Layout',
 'Dwaraka Nagar',
 'Krishna Garden Road',
 'Gubbalala Main Road',
 'RT Nager',
 'Kadathanamale',
 'Manyata Tech Park Nagawara',
 'Chandapura Anekal Road',
 'BEML Layout',
 'Nagavara',
 'Abbigere',
 'HBR Layout 4th Block',
 'Panathur Road',
 'Poornapragna Housing Society L',
 'Wheeler Road Extension',
 'Hegde Nagar',
 'Vasanthapura Main Road',
 'Hennur Road',
 'Telecom Layout Thanisandra',
 'Manayata Tech Park',
 'MS Ramaiah North City Manayata Tech Park',
 'Near Peenya Industrial Area',
 'Bennigana Halli',
 'Jaibharath Nagar Bangalore',
 'Sadashiva Nagar',
 'Ashok Nagar',
 'Kogilu Road Near Yelahanka',
 'Sompura Gate',
 'Bagaluru',
 'Lavelle Road',
 'Horamavu Banjara Lyout',
 'Kundalahalli',
 'Basaveswarnagar',
 'White Field',
 'Yelahanka New Town',
 'Bannerghatta Road Jigani',
 'Hennagara',
 'EPIP Zone',
 'T C Palya Main Road',
 'CV Raman Nagar Kaggadasapura',
 'Ramanjaneyanagar',
 'Chikkanayakanahalli at Off Sarjapur',
 'Ashoka Road',
 'Sindhi Colony',
 'KR Puram Old Madras Road',
 'Bannerghatta',
 'Begur Road',
 'K P Main Road',
 'Residential Flat Uttarahalli Hobli',
 'Bagaluru Near Yelahanka',
 'Ananth Nagar',
 'Electronic City Phase I',
 '6th phase jp nagar',
 'Ramagondanahalli',
 'Jalahalli West',
 'Off Bannerghatta Road',
 'JP Nagar',
 'Mallasandra',
 'JP Nagar Phase 2',
 'Maruthi Sevanagar',
 'Hoskote',
 'Bangalore Road',
 'Residential FlatUttarahalli Hobli',
 '7th Phase JP Nagar',
 'Padmanabha Nagar',
 'Whitefield Road',
 'Nirman Layout',
 'OMBR Layout',
 'Sompura',
 'Medaralli',
 'Bengaluru Kanakapura Road',
 'Basapura Main Road',
 'Gunjur Balagere Road',
 'Hosa Road Electronic City',
 'Budigere',
 'Hennagara Main Road',
 'Off Cunningham Road',
 'Vijaya Bank Layout',
 'Geddalahalli',
 'Banashankari Stage III',
 'Bellari Road',
 'Bhoopasandra',
 'Kachanayakanahalli',
 'Seegehalli Road',
 'HAL']

In [20]:
avg_df.tail()

                                Price         Area  ...  Wardrobe  Refrigerator
Location                                            ...
Yelahanka New Town       3.182000e+06  1150.000000  ...       9.0           9.0
Yerthiganahalli          9.799000e+06  1274.000000  ...       0.0           1.0
Yeshwantpur              1.714271e+07  1977.176471  ...       9.0           9.0
hebbal kempapura         7.250000e+06  1060.000000  ...       9.0           9.0
sarjapura attibele road  6.469972e+06  1153.833333  ...       9.0           9.0

[5 rows x 39 columns]